# Generated by Django 5.1.6 on 2025-03-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия пользователя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email пользователя')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='Город проживания пользователя')),
                ('token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
