# Generated by Django 5.1.6 on 2025-02-22 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название привычки')),
                ('habit_type', models.CharField(choices=[('Полезная', 'Полезная'), ('Приятная', 'Приятная')], default='Полезная', max_length=10, verbose_name='Тип привычки')),
                ('place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место выполнения привычки')),
                ('time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('action', models.CharField(max_length=255, verbose_name='Описание действия')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Является ли привычка приятной')),
                ('frequency', models.CharField(default='Ежедневно', max_length=50, verbose_name='Периодичность')),
                ('reward', models.CharField(max_length=255, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичность привычки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Создатель привычки')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_habits', to='habit.habit')),
            ],
        ),
    ]
