# Generated by Django 5.1.6 on 2025-03-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_remove_habit_habit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение'),
        ),
    ]
