# Generated by Django 5.1.6 on 2025-03-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_habit_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1, verbose_name='Периодичность(Сколько раз в неделю)'),
        ),
    ]
